General refactor
byrnereese/mkdocs-minify-plugin pull request #21
Opened 2022-10-20 13:15 UTC by kamilkrzyskow

This is a continuation of #20 therefore it has had its commits merged to avoid merge conflicts on second PR merge.
The rest of the commits could be squashed into 1 on merge.
It differs slightly compared to #19 as I didn't rename all of the functions and didn't change their order this time, so it should be a more manageable comparison.

2022-10-20 13:36 UTC, kamilkrzyskow commented
I had to force push again, to fix a previous commit message in case it's not being squashed.

2022-10-20 15:10 UTC, wilhelmer commented on README.md
> +A MkDocs plugin to minify HTML, JS or CSS files prior to being written to disk.
It's actually "An MkDocs plugin", because it is pronounced "emkaydocs". See https://www.grammar-monster.com/lessons/an_or_a.htm. Please revert.

2022-10-20 15:15 UTC, wilhelmer requested changes
See comments.

2022-10-20 15:15 UTC, wilhelmer commented on README.md
> +- `cache_safe`:
Please (briefly) explain why the `cache_safe` option is useful.

2022-10-20 15:15 UTC, wilhelmer commented on mkdocs_minify_plugin/plugin.py
> +A MkDocs plugin to minify HTML, JS or CSS files prior to being written to disk
Change to "An MkDocs plugin"

2022-10-20 15:38 UTC, kamilkrzyskow commented on README.md
> +- `cache_safe`:
Done

2022-10-20 20:31 UTC, merged

2022-10-20 20:39 UTC, wilhelmer commented
Here we go, thank you!

@byrnereese Could you please publish v0.6.0 on PyPI? Unfortunately, I don't have the rights to do that.

2022-10-21 10:46 UTC, kamilkrzyskow commented
@wilhelmer 
Thanks a lot for sticking with my not so optimal contribution. Great review process with finding all of those wording issues. 👍 
As for PyPi, maybe adding some Github Action to handle that would be worthwhile in the long run.

2022-10-21 18:59 UTC, byrnereese commented
@wilhelmer 0.6.0 has been deployed.

2022-10-24 06:51 UTC, wilhelmer commented
@byrnereese I added a small bugfix for csscompressor, please deploy v0.6.1, thanks!

2022-11-28 07:59 UTC, wilhelmer commented
@byrnereese Another small bugfix, this time for jsmin. That's the last one for this year, I promise 😉 Please deploy v0.6.2, thanks!

2022-11-28 18:28 UTC, byrnereese commented
@wilhelmer Done!